---
- hosts: all
  become: true
  tasks: 
    - name: Intall all the required nfs services
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nfs-utils
        - nfs-utils-libs
        - portmap
    - name: Start the services and enable 
        service: 
          name: portmap
          state: started
          enabled: yes
    - name: Enable nfs 
        service:
          name: nfs
          state: started
          enabled: yes


  