---
- hosts: Node1
  become: true
  tasks:
    - name: create a directory
      file:
        path: /mnt/nfsshare
        state: directory
        mode: 0755
    - name: create the nfs mount on client
      mount:
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0 
        path: /mnt/nfsshare
        src: '172.31.47.82:/nfsshare'
        state: mounted
