---
- hosts: all
  become: true
  tasks: 
    - name: Intall all the required nfs services
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nfs-utils
        - rpcbind
    - name: start the services 
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - rpcbind
        - nfs

